# Imagen base oficial de Node.js
FROM node:18-slim

# Instala dependencias necesarias para Chromium
RUN apt-get update && apt-get install -y \
    wget \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    && rm -rf /var/lib/apt/lists/*

# Crea carpeta de la app
WORKDIR /usr/src/app

# Copia dependencias
COPY package*.json ./
RUN npm install

# Copia código
COPY . .

# Exponer puerto
EXPOSE 8080

# Comando para correr la app
CMD ["npm", "start"]
